POST  http://127.0.0.1:8000/api/chat/ HTTP/1.1
content-type: application/json

{
    "email": "johndoe@st.knust.edu.gh",
    "message": "i am having a  bad day"
}

###
POST  http://127.0.0.1:8000/api/chat/ HTTP/1.1
content-type: application/json

{
    "email": "johndoe@st.knust.edu.gh",
    "message": "i was frustrated today"
}

###
POST  http://127.0.0.1:8000/api/chat/ HTTP/1.1
content-type: application/json

{
    "email": "johndoe@st.knust.edu.gh",
    "message": "what do i do if i am stressed out?"
}

###
POST  http://127.0.0.1:8000/api/chat/ HTTP/1.1
content-type: application/json

{
    "email": "rubenvordzorgbe@gmail.com",
    "message":"i want to become a thief in future?" 
}